baseURL = "/"
canonifyURLs = false
relativeURLs = true
languageCode = "ru-ru"
title = "AI Orbit"
theme = ""
paginate = 12

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  siteName = "AI Orbit"
  description = "Новости, лайфхаки и проекты об ИИ"

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  page = ["HTML"]

[build]
  future = true
  expired = false
